server.port=9000

spring.cloud.gateway.discovery.locator.enabled=false

spring.cloud.config.fail-fast=false

spring.codec.max-in-memory-size=10MB

spring.cloud.loadbalancer.eager-load.clients=catalogue,commandes
