server.port=9000

spring.cloud.gateway.discovery.locator.enabled=false

spring.cloud.config.fail-fast=false

spring.codec.max-in-memory-size=10MB

spring.cloud.loadbalancer.eager-load.clients=CATALOGUE,COMMANDES,APPDIST-BACKEND

# apigateway.catalogue-uri=lb://CATALOGUE
# apigateway.commandes-uri=lb://COMMANDES
# apigateway.appdist-backend-uri=lb://APPDIST-BACKEND

# If 503 persists (no instance in Eureka), same machine:
apigateway.catalogue-uri=http://127.0.0.1:8095
apigateway.commandes-uri=http://127.0.0.1:8098
apigateway.appdist-backend-uri=http://127.0.0.1:8081

eureka.client.registry-fetch-interval-seconds=5

# Keycloak / JWT validation by API Gateway (Resource Server)
# Change realm if needed. Example default Keycloak URL:
# http://localhost:8080/realms/microservices-realm
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/microservices-realm
